services:
  my-springboot-mongo-app:
    image: vivek081141/springboot-sample-app:latest
    container_name: springboot-sample-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    platform: linux/arm64
volumes:
  mongo-data:
    driver: local


