server:
  port: 18012
  servlet:
    context-path: /starter

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: mongoboot

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true