apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-springboot-mongo-app
  template:
    metadata:
      labels:
        app: my-springboot-mongo-app
    spec:
      containers:
        - name: my-springboot-mongo-app
          image: vivek081141/my-springboot-mongo-app:latest
          ports:
            - containerPort: 18012
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: mongodb
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: mongoboot
            - name: SPRING_PROFILES_ACTIVE
              value: prod
      nodeSelector:
        kubernetes.io/arch: arm64
---
apiVersion: v1
kind: Service
metadata:
  name: my-springboot-mongo-app
spec:
  ports:
    - port: 18012
      targetPort: 18012
  selector:
    app: my-springboot-mongo-app